<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV6j0Ema\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV6j0Ema/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV6j0Ema.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV6j0Ema\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV6j0Ema\App_KernelDevDebugContainer([
    'container.build_hash' => 'V6j0Ema',
    'container.build_id' => 'a6d102a3',
    'container.build_time' => 1744475703,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV6j0Ema');
