<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAMAZ5kM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAMAZ5kM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAMAZ5kM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAMAZ5kM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAMAZ5kM\App_KernelDevDebugContainer([
    'container.build_hash' => 'AMAZ5kM',
    'container.build_id' => '813e2484',
    'container.build_time' => 1745684906,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAMAZ5kM');
