<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'actu' => [[], ['_controller' => 'App\\Controller\\ActuController::fetchPosts'], [], [['text', '/actu']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], [], []],
    'add_user' => [[], ['_controller' => 'App\\Controller\\AdminController::manageUser'], [], [['text', '/admin/user/add']], [], [], []],
    'edit_user' => [['id'], ['id' => null, '_controller' => 'App\\Controller\\AdminController::manageUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/user/edit']], [], [], []],
    'delete_user' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/delete/user']], [], [], []],
    'delete_ue' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteUe'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/delete/ue']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/']], [], [], []],
    'moodle' => [[], ['_controller' => 'App\\Controller\\MoodleController::index'], [], [['text', '/moodle']], [], [], []],
    'post_ue' => [[], ['_controller' => 'App\\Controller\\PostUeController::index'], [], [['text', '/post-ue']], [], [], []],
    'prof_course' => [[], ['_controller' => 'App\\Controller\\ProfCourseController::index'], [], [['text', '/prof_course']], [], [], []],
    'student_course' => [[], ['_controller' => 'App\\Controller\\StudentCourseController::index'], [], [['text', '/student_course']], [], [], []],
    'App\Controller\ActuController::fetchPosts' => [[], ['_controller' => 'App\\Controller\\ActuController::fetchPosts'], [], [['text', '/actu']], [], [], []],
    'App\Controller\AdminController::index' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], [], []],
    'App\Controller\AdminController::deleteUser' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/delete/user']], [], [], []],
    'App\Controller\AdminController::deleteUe' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteUe'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/delete/ue']], [], [], []],
    'App\Controller\LoginController::index' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\MoodleController::index' => [[], ['_controller' => 'App\\Controller\\MoodleController::index'], [], [['text', '/moodle']], [], [], []],
    'App\Controller\PostUeController::index' => [[], ['_controller' => 'App\\Controller\\PostUeController::index'], [], [['text', '/post-ue']], [], [], []],
    'App\Controller\ProfCourseController::index' => [[], ['_controller' => 'App\\Controller\\ProfCourseController::index'], [], [['text', '/prof_course']], [], [], []],
    'App\Controller\StudentCourseController::index' => [[], ['_controller' => 'App\\Controller\\StudentCourseController::index'], [], [['text', '/student_course']], [], [], []],
];
